### PR TITLE
Finishing emmintrin.d except for load/storeUnaligned and shuffleVector

### PR DESCRIPTION
**Pull request by baziotis**
I changed all the `emmintrin.d`. The PR might seem a little big but it's actually quite repetitive.
I left all but `load/storeUnaligned` and `shuffleVector`. These seem to need special treatment that I'm not sure yet how to do. I'll probably have something eventually but if you have any recommendation, feel free.

### CODE REVIEW

**Comment by p0nce** [comment]
About the `.array` thing: is there a GDC version that allows to do without it? I'm not quite sure it will work OK in other compilers. I will be adding a test to see if mutability goes well.

**Comment by baziotis** [comment]
It should work. AFAIK, it is more general than the `VectorOps` that does the operator overloading. Basically, I think that in GDC, one has to do manual `.array` because the `VectorOps` `mixin` does not add the operator overloads (I don't know exactly why). Other compilers should be just fine with this, it just results in slightly uglier code.

Btw, the errors that were in other compilers before my last commit were because by mistake I used `.array` on types that were actual arrays (e.g. `byte[8]`). In such cases, it is of course wrong D.

**Comment by p0nce** [comment]
Thanks for the PR! Much appreciated :)

**Comment by baziotis** [comment]
Don't mention it, I hope that in the end we will succeed to fully support GDC!
I will do a trivial PR fixing some `.array` things so that asserts and stuff that I saw on Travis pass
and then I'll come back to load, store and shuffle.

**Comment by p0nce** [comment]
Yes, if you can do SSE1 and SSE3 it would be awesome :) I can manage to fix some stuff too since I get the same errors than travis here.

**Comment by p0nce** [comment]
Also don't forget to add your Copyright to every file you touch!

**Comment by baziotis** [comment]
> Also don't forget to add your Copyright to every file you touch!

You mean the Authors section. Right, I missed that. :)

**Comment by baziotis** [comment]
> Yes, if you can do SSE1 and SSE3 it would be awesome :)

You mean the `load/storeUnaligned` and shuffle right? Yes, I tried to finish the rest of work (i.e. get only errors related to this) as it needs some thought. The GCC builtins don't seem to have a 1-1 mapping with the intel intrinsics.

**Comment by p0nce** [comment]
You can remove the Authors Ddoc section, it's not really useful as compared to the Copyright DDoc section :)

**Comment by baziotis** [comment]
I have never added a copyright somewhere. You mean something like this:
`* Copyright: Copyright Auburn Sounds 2016-2019, Stefanos Baziotis 2019`
?

**Comment by p0nce** [comment]
Yes, this is important to add this. 

Beware I'm fixing some GDC error, I have loadUnaligned working and fixed some errors.

**Comment by baziotis** [comment]
Great! I'm looking forward to the changes.

**Pull request merged**
