### PR TITLE
emmintrin.d fixes

### PR DESCRIPTION
**Pull request by baziotis**
Please give it a little time so that I can see the Travis errors. I don't know why, but some errors are not visible when I compile.

### CODE REVIEW

**Comment by p0nce** [comment]
May I merge now? Travis says there are no more build errors for emmintrin.d

**Comment by baziotis** [comment]
Yes, it's ok from me. There are some errors on pmmintrin on Mac OS but I think you saw that. :/

**Comment by p0nce** [comment]
mmm No didn't saw the pmmintrin errors. Damn

**Comment by p0nce** [comment]
I'm fixing the emmintrin.d errors right now!

**Comment by baziotis** [comment]
There are more emmintrin errors?

**Comment by p0nce** [comment]
Yes !

**Comment by p0nce** [comment]
Once you deblock a pass of the compiler, it unlocks new errors for the whole codebase

**Comment by baziotis** [comment]
I'm right now so I cant run but travis doesnt show anything. I guess you fixed other errors in other files and that deblcked a pass that revealed more errors on emmintrin. Good luck!

**Comment by p0nce** [comment]
Now I have no more build errors with local GDC `x86_64-unknown-linux-gnu-gdc.exe (gdcproject.org 20161222-v2.068.2_gcc6) 6.3.0`, however unittest don't even start. I'm taking a pause, this stuff is strangely exhausting

**Comment by baziotis** [comment]
Yes cause it's robotic and repetitive.. And when it's not it's a little boring.
But hey, intel-intrinsics will support GDC in the end. ;)

**Pull request merged**
