### PR TITLE
Fix the generic implementation of _mm_alignr_epi8 and _mm_alignr_pi8

### PR DESCRIPTION
**Pull request by ibuclaw**
Looking at 5b48c0d67629bc033787101191b76951f222607b, it looks like `_mm_alignr_pi8` would be wrong for the same reasons too.

### CODE REVIEW

**Comment by p0nce** [comment]
Oh crap also did it in cc78395b85c81ab6ce51d74350e6acebefd23ef2

**Comment by p0nce** [comment]
Thanks for support! Test is up and running

**Comment by ibuclaw** [comment]
Fixed `_mm_alignr_pi8` too, and confirmed it vs. hardware instruction.  Looks like I have conflicts though. >:-)

**Comment by p0nce** [comment]
I will take your _mm_alignr_pi8 verbatim and my _mm_alignr_epi8

**Comment by ibuclaw** [comment]
Rebased on top of cc78395.

**Comment by p0nce** [comment]
I do it, the LDC branch does not build as is in your version.

**Comment by p0nce** [comment]
phew, fixed in v1.4.2

**Pull request closed without merging**
