### PR TITLE
Eliminating almost completely shufflevector for GDC_X86

### PR DESCRIPTION
**Pull request by baziotis**
It doesn't eliminate it in some stores and loads that I think I can get it to do it with `shufps` or smth.

Also, as a side-note, I think that it's better to move all the code instead of the form:
```
func_decl()
{
    static if (GDC_X86)
    {
        return builtin();
    }
    else
    {
        other code
    }
}
```

and instead `alias` the builtin.

I know _I_ took the initiative to use that form. So, I propose to take the initiative to remove it. :P
The reasoning is that I believe it pressures less to the compiler.
Also, since a lot of these builtins are common between LDC and GDC, we can throw an `enum GDC_LDC` for when we are in either `GDC_X86` or `LDC`.

### CODE REVIEW

**Comment by p0nce** [comment]
Just an `alias` often doesn't work since the __builtin signature is often different enough from the intel-intrinsics signature. `alias` must be attempted first if it works, but often typechecking reveals that it doesn't.

**Comment by p0nce** [comment]
> Also, since a lot of these builtins are common between LDC and GDC, we can throw an enum GDC_LDC for when we are in either GDC_X86 or LDC.

More often than not they are not common at all! LDC has MUCH less such builtins, and I'd rather keep the LDC and GDC functions separate. Amongst the builtins you submitted, I think LDC has none of them.

**Comment by p0nce** [comment]
I'm working on mmx.d !

**Comment by baziotis** [comment]
I'm not familiar with `ldc.gccbuiltins_x86`. Doesn't it have all the intrinsics that we have used?
IIRC, a lot of times I copied an alias from `version (LDC)` which was a GCC alias.

**Comment by baziotis** [comment]
> I'm working on mmx.d !

Success story :D.

**Comment by p0nce** [comment]
> Doesn't it have all the intrinsics that we have used?

It has only a subset, and they tend to disappear over time. So for LDC, the design goal is to avoid builtin as much as possible, if there is another way to generate the right (er, speedier) instruction. 

For GDC, it seems we have no choice but similarly if there is a way to have an instruction with normal D code we can check on https://explore.dgnu.org/ and then remove builtin usage. This is a rather slow process...

**Comment by baziotis** [comment]
Yes, I see. After there is support to GDC, we can then move to builtin removal.

**Comment by baziotis** [comment]
I guess you're currently working on pmmintrin.d so I will fix some things in emmintrin.d

**Comment by p0nce** [comment]
Yes! Just finished it, and now xmmintrin.d starts coming up. 
And that's _before_ we start with unittest results :)

**Pull request merged**
