### PR TITLE
Add _mm256_storeu_si256 (AVX)

### PR DESCRIPTION
**Pull request by JohanEngelen**

### CODE REVIEW

**Comment by p0nce** [comment]
Doesn't pass tests.

**Comment by JohanEngelen** [comment]
these are known errors of master, right?

**Comment by p0nce** [comment]
Yes. I'm sorry I was in a bad day.

**Comment by JohanEngelen** [comment]
> Yes. I'm sorry I was in a bad day.

Hope you had a better day today!
Did you intend to merge instead of close? ;)

**Comment by p0nce** [comment]
Ah yes indeed, was a mis-click ! Damn.

**Comment by p0nce** [comment]
All green now

**Pull request merged**
